name: Tests Unchanged

on:
  workflow_dispatch:

jobs:
  change-check-workflow:
    uses: markpatterson27/GitHub-Classroom-Check-For-Changes/.github/workflows/change-check.yml@main

  change-check-workflow-with-input:
    uses: markpatterson27/GitHub-Classroom-Check-For-Changes/.github/workflows/change-check.yml@main
    with:
      paths: .github */tests */*/tests